# private actions
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          context: .
          who-to-greet: 'Wanlu and Xiaogouji'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

# # public actions
# on: [push]

# jobs:
#   hello_world_job:
#     runs-on: ubuntu-latest
#     name: A job to say hello
#     steps:
#       - name: Hello world action step
#         id: hello
#         uses: actions/hello-world-docker-action@v2
#         with:
#           who-to-greet: 'Wanlu and Xiaogouji'
#       # Use the output from the `hello` step
#       - name: Get the output time
#         run: echo "The time was ${{ steps.hello.outputs.time }}"

